### ISSUE TITLE
Black overlay?

### ISSUE THREAD

**Issue by toothie96** [deg0nz/MagicMirror-Display-Controller#1]
Would there be a way of creating a black overlay to the screen as opposed to turning the screen off. I ask as I use the in-built monitor speakers, so it would be handy if the screen could look turned off, when in actual fact it's just got a full-screen black box on it.

**Comment by deg0nz** [comment]
Hey @toothie96,

Unfortunately that is not possible to do by my little script. It would be better if you kind of modify the [MMM-PIR-Sensor](https://github.com/paviro/MMM-PIR-Sensor) module or write a module your own (or ask someone in the [forum](forum.magicmirror.builders) to do that for you).

There's one thing that bugs me about your request: 
Why don't leave the display turned on all the time? The main purpose of my script is to save energy when the mirros is not needed and save the life time of the LCD display. Your request doesn't fit with any of those two tings.

**Comment by deg0nz** [comment]
Since nothing happened here for about 4 months, I'm closing this issue.
If you have any questions, feel free to reopen this issue.
