### ISSUE TITLE
keeps on looping

### ISSUE THREAD

**Issue by bachoo786** [deg0nz/MagicMirror-Display-Controller#2]
thanks for the code

I have set it up however when I run it, it keeps on looping giving me:

```
Motion detected! Setting timer to 240 seconds.
Timer: 240 seconds
Motion detected! Setting timer to 240 seconds.
Timer: 240 seconds
Motion detected! Setting timer to 240 seconds.
Timer: 240 seconds
.......
...........
```

Can you help please?

**Comment by benoitdansereau** [comment]
Hi,

You may have your sensor wired incorrectly.  I know since it happened to me!

**Comment by deg0nz** [comment]
I will close this because of inactivity. If you encounter an issue, please feel free to open it again
