### ISSUE TITLE
empty log file

### ISSUE THREAD

**Issue by GattoJohnny** [deg0nz/MagicMirror-Display-Controller#3]
Hello,

I've been using this module for more than a year now. It works great, I like it very much. 
In spite of this long life span the log file has always been empty. 
Can you, please, tell me what events should be listed in the log and what I might do wrong?

/lib/systemd/system/pir_sensor.service:

```
[Unit]
Description=MagicMirror PIR Service
After=multi-user.target

[Service]
Type=idle
ExecStart=/usr/bin/python /home/pi/MagicMirror/modules/MagicMirror-Display-Controller/pir.py > /home/pi/MagicMirror/modules/MagicMirror-Display-Controller/pir_sensor.log 2>&1

[Install]
WantedBy=multi-user.target
```

Permissions of /home/pi/MagicMirror/modules/MagicMirror-Display-Controller/pir_sensor.log:

`-rw-rw-rw-  1 pi pi    0 Dec 11 21:53 pir_sensor.log`

Thanks ahead.

**Comment by deg0nz** [comment]
Yes, you are absolutely right... I haven't noticed that, because I use `journalctl` for looking into the logging. 
I think we can remove the log file output from the unit file since we are using a systemd service here anyways. You can access the logs with the following command:

`sudo journalctl -u pir_sensor.service`

**Comment by GattoJohnny** [comment]
Thanks for the prompt assistance. 
I'm quite a beginner to Linux so not sure what you mean by "_remove the log file output from the unit file_". Do you suggest replacing this line:

`ExecStart=/usr/bin/python /home/pi/MagicMirror/modules/MagicMirror-Display-Controller/pir.py > /home/pi/MagicMirror/modules/MagicMirror-Display-Controller/pir_sensor.log 2>&1`

with this line

`ExecStart=/usr/bin/python /home/pi/MagicMirror/modules/MagicMirror-Display-Controller/pir.py`

in /lib/systemd/system/pir_sensor.service ?

**Comment by deg0nz** [comment]
Sorry for the late response. Yes, I mean exactly this :)
