### ISSUE TITLE
cyclic ON/OFF at night

### ISSUE THREAD

**Issue by GattoJohnny** [deg0nz/MagicMirror-Display-Controller#4]
I couple of days ago I spent the night reading a book. Far away from the mirror, out of the sensing distance, but in the same room. It went ON and OFF periodically, roughly once every15-20 minutes. The following nights I checked it again and again and seems to be the normal behavior, ever since it's been operating. Let me stress out that during day time it works like charm and gave no cause for suspicion.

Log proves it to be a regular, cyclical event. Pretty accurate, as a matter of fact.

```
  ON	  OFF
3:54:47	3:59:49
4:10:47	4:15:49
4:26:47	4:31:49
4:42:47	4:47:49
4:58:47	5:03:49
5:14:47	5:19:49
5:30:47	5:35:49
5:46:47	5:51:49
6:02:47	6:07:49
6:18:47	6:23:49
6:34:47	6:39:49
```

The monitor turns on, stays on for 5 minutes and 2 seconds (timeUntilDisplayOff = 300 ms).
Then turns off, stays off for 10 minutes and 58 seconds, then the whole cycle starts over.

PM2 restarts mm at 4:20 every night. Should it affect these monitor on/off events, it would be seen in the pir_sensor.service log. However, it does not. 

Does it work like that by design? Did I wire something incorrectly? Any ideas?

**Comment by deg0nz** [comment]
Oh. That is a pretty strange behaviour. I never spotted that on my mirror... I'm going to investigate this when I find time to do so.

> PM2 restarts mm at 4:20 every night. Should it affect these monitor on/off events, it would be seen in the pir_sensor.service log. However, it does not.

No, that should not be the case

> Does it work like that by design? Did I wire something incorrectly? Any ideas?

No, this is definitely not by design. Currently no idea... If you wired it incorrectly, I think this would also affect the behaviour at day time

**Comment by soubhik-khan** [comment]
I have been spending hour figuring out random motion detected by the SR-501 sensor. After lots of googling and trying it myself i'm certain that the SR-501 has lots of noise - false positive motion detection! best to get a digital sensor like AM-312 or extend the jumper cable for SR-501 and add some resistor+capacitor to the signal pi(It worked me)

**Comment by GattoJohnny** [comment]
For me it could be an OS or core MM related issue. The problem cannot be reproduced any more on a newer Buster version and MM 2.12.
Anyways, let me thank @deg0nz again for this great program.
