### ISSUE TITLE
Changing command

### ISSUE THREAD

**Issue by DrunkMonkey45** [deg0nz/MagicMirror-Display-Controller#5]
Hello,

Trying to adjust the code to work with cec-client commands instead of vcgencmd', 'display_power? I.E. running a command like `echo` 'on 0' | cec-client -s -d 1 instead.

**Comment by DrunkMonkey45** [comment]
I found that changing the vcgencmd line to the below code caused the desired effects of display control

Change words display number to the address of your cec device 

Off
subprocess.call("echo 'standby *DISPLAY NUMBER*' | cec-client -s -d 1", shell=True

On
subprocess.call("echo 'on *DISPLAY NUMBER*' | cec-client -s -d 1", shell=True

**Comment by deg0nz** [comment]
Closed due to inactivity. Feel free to open again if necessary.
